package message

import json "github.com/goccy/go-json"

// Role defines the participant's context in a conversation.
// This standardization ensures all integrated LLM providers map correctly to a unified identity schema,
// preventing vendor-specific role bleed (e.g., Anthropic's "user" vs OpenAI's "system").
type Role string

const (
	// RoleSystem sets the global behavior and constraints for the assistant.
	// It should typically be the first message and not change mid-conversation.
	RoleSystem Role = "system"

	// RoleUser is the prompt from the end-user.
	RoleUser Role = "user"

	// RoleAssistant is the completion generated by the model.
	// This can contain text, reasoning steps, or tool execution requests.
	RoleAssistant Role = "assistant"

	// RoleTool is the result returned by executing a requested tool.
	// A RoleTool message MUST directly follow a RoleAssistant message that requested it.
	RoleTool Role = "tool"
)

// TextTurn is a convenience builder for simple text-only conversation turns.
// Useful when constructing static prompts without multimodal or tool-call requirements.
func TextTurn(role Role, text string) Turn {
	return Turn{Role: role, Parts: []Part{TextPart{Text: text}}}
}

// Part forms the atomic content layer of a Turn, allowing multimodal and complex nested structures
// (e.g., mixing text, images, and tool responses) under a single Role.
type Part interface {
	isPart() // unexported marker method to ensure interface constraint
}

// TextPart represents conventional string payload within a Turn.
// This is the primary driver for textual interaction and context propagation.
type TextPart struct {
	Text string
}

func (TextPart) isPart() {}

// ThoughtPart exposes the model's internal reasoning process (e.g., Chain of Thought).
// Providers that support reasoning loops typically emit this before generating the final TextPart.
type ThoughtPart struct {
	Text string
}

func (ThoughtPart) isPart() {}

// ToolCallPart represents an instruction from the model to execute an external function.
// Providers will halt generation upon emitting this and wait for a subsequent RoleTool response.
type ToolCallPart struct {
	// ID uniquely identifies the call. It is used to match the ToolResultPart back to this request.
	ID               string
	// Name matches the registered ToolDefinition's name.
	Name             string
	// Arguments contains the raw JSON schema payload provided by the model.
	Arguments        json.RawMessage
	// ThoughtSignature is used by some providers (like Gemini) to verify context continuity across tool turns.
	ThoughtSignature []byte
}

func (ToolCallPart) isPart() {}

// ToolResultPart feeds the output of an executed tool back into the conversation context.
// Must be paired with a Turn using RoleTool.
type ToolResultPart struct {
	// ToolCallID must precisely match the ID from the prior ToolCallPart.
	ToolCallID string
	// Content contains the stringified execution result (often JSON).
	Content    string
}

func (ToolResultPart) isPart() {}

// ToolDefinition describes the schema and capabilities of an external function.
// This is passed to the provider to instruct it on what tools are available and how to formulate the arguments.
type ToolDefinition struct {
	// Type specifies the class of tool (e.g., "function" for standard API calls, "web_search_20250305" for native integrations).
	Type        string
	// Name must match the identifier expected by the provider for invoking this specific capability.
	Name        string
	// Description guides the model on when and why to invoke this tool.
	Description string
	// Parameters defines the expected JSON Schema for the argument payload.
	Parameters  json.RawMessage
}

// ChatOptions configure the non-prompt generation parameters for the LLM.
// These are applied at the request level, overriding any provider-level defaults if specified.
type ChatOptions struct {
	// Tools registers available capabilities for the model.
	Tools       []ToolDefinition
	// JSONMode forces the model to only output strictly valid JSON.
	JSONMode    bool
	// Temperature controls generation randomness (higher = more creative, lower = more deterministic).
	Temperature *float64
	// TopP restricts vocabulary selection to tokens comprising the top probability mass.
	TopP        *float64
	// MaxTokens sets a hard limit on the generated response length.
	MaxTokens   *int
	// Stop defines sequence boundaries that immediately halt generation.
	Stop        []string
}

// WithDefaults creates a finalized option set by filling any nil values in the current ChatOptions
// with the fallbacks provided in 'd' (usually coming from global config).
func (o ChatOptions) WithDefaults(d ChatOptions) ChatOptions {
	if o.Temperature == nil {
		o.Temperature = d.Temperature
	}
	if o.TopP == nil {
		o.TopP = d.TopP
	}
	if o.MaxTokens == nil {
		o.MaxTokens = d.MaxTokens
	}
	if len(o.Stop) == 0 {
		o.Stop = d.Stop
	}
	return o
}

// ToolCall is the deserialized invocation request from a provider.
// This structure holds the necessary state for the execution engine to route and call the designated tool.
type ToolCall struct {
	// ID correlates the call with its upcoming result in the conversation flow.
	ID               string
	// Name specifies the function logic to invoke.
	Name             string
	// Arguments is the raw JSON schema payload; it must be parsed against the expected ToolDefinition struct.
	Arguments        json.RawMessage
	// ThoughtSignature stores opaque continuity tokens needed by specific providers (e.g., Gemini) for context resumption.
	ThoughtSignature []byte
}

// ParseArguments is a strongly-typed helper for decoding the raw json Arguments of a ToolCall
// into the explicit parameter struct expected by the tool implementation.
func ParseArguments[T interface{}](tc ToolCall, target *T) error {
	return json.Unmarshal(tc.Arguments, target)
}
